# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
[dev]
  framework = "vite"
  command = "npm run dev" # Command to start your dev server
  port = 3001 # Port that the dev server will be listening on
  targetPort = 3000 # Port that the dev server is running on
  functions = "netlify/functions"
  publish = "dist" # Folder with the static content for _redirect file
[functions]
  node_bundler = "esbuild"
